# Generated by Django 2.2.5 on 2019-11-14 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='last_message',
            field=models.TextField(null=True, verbose_name='Текст последнего сообщения'),
        ),
    ]
