# Generated by Django 2.2.5 on 2019-11-14 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_attachment_last_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='last_message',
        ),
    ]
