# Generated by Django 2.2.5 on 2019-11-28 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_attachment_last_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='login',
            field=models.CharField(max_length=10, null=True, unique=True, verbose_name='Логин'),
        ),
    ]
