# Generated by Django 2.2.5 on 2019-11-14 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_message_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='last_message',
            field=models.TextField(null=True, verbose_name='Текст последнего сообщения'),
        ),
    ]
